# Generated by Django 2.2.19 on 2021-04-03 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subcategories', '0003_subcategory_category'),
        ('products', '0003_auto_20210329_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='subcategories.Subcategory'),
            preserve_default=False,
        ),
    ]
